/**
 * local-kb 首次建库脚本。
 *
 * 用法：
 *   bun run scripts/setup.ts <kb-path> --schema <schema.yaml>
 *   bun run scripts/setup.ts <kb-path> --mock              # 使用内置 mock schema
 *
 * 流程：
 *   1. 解析 schema.yaml（极简 YAML 解析器，零依赖）
 *   2. 生成 .schema.sql（含 FTS5 + 触发器 + 索引）
 *   3. 跑 ensureSchema 幂等建表
 *   4. 写 slug_rule.json（供 ingest.ts 用）
 *   5. 写 README 模板
 *   6. 写 .schema-version 文件
 *
 * 反模式（直接报错）：
 *   - schema.yaml 缺必填字段 → 报错
 *   - 库目录已存在且非空 → 报错（避免覆盖）
 *   - .schema.sql 已存在 → 报错（提示用户用 migrate）
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveKbPath, ensureSchema, describeDb } from "./db.ts";
import { parseYaml, type YamlObject } from "./yaml.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ===== Schema 解析 =====

interface FieldDef {
  name: string;
  type: string;
  unique?: boolean;
  indexed?: boolean;
  fts?: boolean;
  json?: boolean;
  related?: boolean;  // 该字段参与 related.ts 的默认关联发现
}

interface SchemaYaml {
  collection: {
    name: string;
    schema_version: number | string;
    primary_table: string;
    primary_key?: string;
  };
  fields: {
    required: FieldDef[];
    optional?: FieldDef[];
  };
  slug_rule?: {
    parts: Array<{ field: string; transform?: string }>;
    separator?: string;
    unique_fields?: string[];
  };
}

function loadSchemaYaml(path: string): SchemaYaml {
  if (!existsSync(path)) {
    throw new Error(`schema.yaml not found: ${path}`);
  }
  const obj = parseYaml(readFileSync(path, "utf-8"));

  // 必填字段校验
  if (!obj.collection) throw new Error("schema.yaml 缺少 collection 节");
  const c = obj.collection as YamlObject;
  if (!c.name) throw new Error("schema.yaml 缺少 collection.name");
  if (!c.schema_version) throw new Error("schema.yaml 缺少 collection.schema_version");
  if (!c.primary_table) throw new Error("schema.yaml 缺少 collection.primary_table");

  if (!obj.fields) throw new Error("schema.yaml 缺少 fields 节");
  const f = obj.fields as YamlObject;
  if (!f.required) throw new Error("schema.yaml 缺少 fields.required");

  return obj as unknown as SchemaYaml;
}

// ===== SQL 生成 =====

const SQL_TYPE_MAP: Record<string, string> = {
  string: "TEXT",
  int: "INTEGER",
  integer: "INTEGER",
  number: "REAL",
  text: "TEXT",
  iso8601: "TEXT",
  date: "TEXT",
  path: "TEXT",
  boolean: "INTEGER",
  "string[]": "TEXT NOT NULL DEFAULT '[]'",
};

function generateSchemaSql(schema: SchemaYaml): string {
  const { primary_table, schema_version } = schema.collection;
  const primaryKey = schema.collection.primary_key ?? "slug";

  const allFields: FieldDef[] = [
    ...schema.fields.required,
    ...(schema.fields.optional ?? []),
  ];

  // 主表
  const colDefs: string[] = [];
  for (const f of allFields) {
    if (f.name === primaryKey) continue; // 主键单独定义
    const sqlType = SQL_TYPE_MAP[f.type] ?? "TEXT";
    const notNull = schema.fields.required.some((r) => r.name === f.name) ? " NOT NULL" : "";
    const unique = f.unique ? " UNIQUE" : "";
    colDefs.push(`  ${f.name} ${sqlType}${notNull}${unique}`);
  }
  const pkType = allFields.find((f) => f.name === primaryKey)?.type === "int" ? "INTEGER" : "TEXT";

  let sql = `-- schema_version: ${schema_version}\n`;
  sql += `-- primary_table: ${primary_table}\n`;
  sql += `-- primary_key: ${primaryKey}\n`;
  sql += `-- generated by local-kb setup.ts at ${new Date().toISOString()}\n`;
  sql += `-- DO NOT EDIT THIS FILE MANUALLY — use migrate to update schema\n\n`;

  sql += `CREATE TABLE IF NOT EXISTS ${primary_table} (\n`;
  sql += `  ${primaryKey} ${pkType} PRIMARY KEY,\n`;
  sql += colDefs.join(",\n");
  sql += `\n);\n\n`;

  // FTS5 虚拟表
  const ftsFields = allFields.filter((f) => f.fts);
  if (ftsFields.length > 0) {
    const ftsCols = ftsFields.map((f) => f.name).join(", ");
    sql += `CREATE VIRTUAL TABLE IF NOT EXISTS ${primary_table}_fts USING fts5(\n`;
    sql += `  ${ftsCols},\n`;
    sql += `  content='${primary_table}', content_rowid='rowid',\n`;
    sql += `  tokenize='unicode61 remove_diacritics 2'\n`;
    sql += `);\n\n`;

    // 触发器
    const ftsInsert = ftsFields.map((f) => `COALESCE(new.${f.name}, '')`).join(", ");
    const ftsDelete = ftsFields.map((f) => `COALESCE(old.${f.name}, '')`).join(", ");

    sql += `CREATE TRIGGER IF NOT EXISTS ${primary_table}_ai AFTER INSERT ON ${primary_table} BEGIN\n`;
    sql += `  INSERT INTO ${primary_table}_fts(rowid, ${ftsCols}) VALUES (new.rowid, ${ftsInsert});\n`;
    sql += `END;\n\n`;

    sql += `CREATE TRIGGER IF NOT EXISTS ${primary_table}_ad AFTER DELETE ON ${primary_table} BEGIN\n`;
    sql += `  INSERT INTO ${primary_table}_fts(${primary_table}_fts, rowid, ${ftsCols}) VALUES('delete', old.rowid, ${ftsDelete});\n`;
    sql += `END;\n\n`;

    sql += `CREATE TRIGGER IF NOT EXISTS ${primary_table}_au AFTER UPDATE ON ${primary_table} BEGIN\n`;
    sql += `  INSERT INTO ${primary_table}_fts(${primary_table}_fts, rowid, ${ftsCols}) VALUES('delete', old.rowid, ${ftsDelete});\n`;
    sql += `  INSERT INTO ${primary_table}_fts(rowid, ${ftsCols}) VALUES (new.rowid, ${ftsInsert});\n`;
    sql += `END;\n\n`;
  }

  // 索引
  const indexedFields = allFields.filter((f) => f.indexed || f.unique);
  for (const f of indexedFields) {
    if (f.name === primaryKey) continue;
    sql += `CREATE INDEX IF NOT EXISTS idx_${primary_table}_${f.name} ON ${primary_table}(${f.name});\n`;
  }
  sql += "\n";

  // schema_meta
  sql += `CREATE TABLE IF NOT EXISTS schema_meta (\n`;
  sql += `  key   TEXT PRIMARY KEY,\n`;
  sql += `  value TEXT NOT NULL\n`;
  sql += `);\n`;

  return sql;
}

// ===== Slug rule 生成 =====

function generateSlugRuleJson(schema: SchemaYaml): string {
  // 收集 related: true 字段，写入 related_fields 数组（供 related.ts 默认值用）
  const allFields: FieldDef[] = [
    ...schema.fields.required,
    ...(schema.fields.optional ?? []),
  ];
  const relatedFields = allFields
    .filter((f) => f.related)
    .map((f) => f.name);
  const rule: Record<string, unknown> = {
    ...(schema.slug_rule ?? { parts: [], separator: "_" }),
    related_fields: relatedFields,
  };
  return JSON.stringify(rule, null, 2);
}

// ===== README 模板 =====

function generateReadme(schema: SchemaYaml): string {
  return `# ${schema.collection.name} — 本地知识库

> **路径**：${schema.collection.name}/
> **后端**：SQLite + FTS5
> **schema_version**：v${schema.collection.schema_version}
> **建立日期**：${new Date().toISOString().slice(0, 10)}

## 调用命令

\`\`\`bash
# 入库
bun run scripts/ingest.ts . --meta items/<slug>/meta.yaml

# 反查
bun run scripts/query.ts . --doi <doi>
bun run scripts/query.ts . --fts "<关键词>"

# 关联
bun run scripts/related.ts . --slug <slug>

# 备份
bun run scripts/backup.ts .
\`\`\`

## 字段定义

详见 \`.schema.sql\` 和 \`schema.yaml\`。

## 已知反模式（详见 local-kb SKILL.md）

- ❌ 不算 slug 就 mkdir
- ❌ 用户口述的硬事实写成"❓ 待核实"
- ❌ OCR 数值 100% 信任
- ❌ backup 文件名按字典序排

## 备份策略

详见 \`schema.yaml\` 的 backup 节。
`;
}

// ===== Mock schema（自测用） =====

function mockSchemaYaml(): string {
  return `collection:
  name: "test-kb"
  schema_version: 1
  primary_table: items
  primary_key: slug

fields:
  required:
    - { name: title,         type: string }
    - { name: first_author,  type: string, related: true }
    - { name: year,          type: int }
    - { name: fetched_at,    type: iso8601 }
  optional:
    - { name: doi,           type: string, unique: true }
    - { name: tags,          type: "string[]", json: true, related: true }
    - { name: abstract,      type: text, fts: true }
    - { name: fulltext,      type: text, fts: true }
    - { name: journal,       type: string, related: true }

slug_rule:
  parts:
    - { field: first_author, transform: "lower+strip_nonascii" }
    - { field: year }
    - { field: journal,      transform: "lower+strip_nonascii+slice(12)" }
    - { field: title,        transform: "lower+strip_nonascii+split_space+slice_words(4)+join_underscore" }
  separator: "_"
  unique_fields: [doi]
`;
}

// ===== CLI =====

function parseArgs(): {
  kbPath: string | null;
  schemaPath: string | null;
  mock: boolean;
} {
  let kbPath: string | null = null;
  let schemaPath: string | null = null;
  let mock = false;
  for (let i = 2; i < process.argv.length; i++) {
    const a = process.argv[i];
    const next = process.argv[i + 1];
    if (a === "--schema" && next) {
      schemaPath = resolve(next);
      i++;
    } else if (a === "--mock") {
      mock = true;
    } else if (a === "--help" || a === "-h") {
      console.log(`用法: setup.ts <kb-path> [options]
  <kb-path>              库路径（如 ./my-kb 或 C:/Data/MyKB）
  --schema <file>        schema.yaml 路径
  --mock                 使用内置 mock schema（自测用）
  --help, -h             本帮助
`);
      process.exit(0);
    } else if (!kbPath) {
      kbPath = resolve(a);
    }
  }
  return { kbPath, schemaPath, mock };
}

const args = parseArgs();
if (!args.kbPath && !args.mock) {
  console.error("需要 <kb-path> 或 --mock，或 --help");
  process.exit(1);
}

const kbPath = args.kbPath ?? "./test-kb";
const { rootDir } = resolveKbPath(kbPath);

// 1. 检查目录状态
if (existsSync(rootDir)) {
  const entries = readdirSync(rootDir);
  if (entries.length > 0) {
    console.error(`>>> 错误：${rootDir} 目录已存在且非空（${entries.length} 项）`);
    console.error(`>>> 如需重建，请先删除该目录或用 migrate.ts 升级 schema`);
    process.exit(1);
  }
} else {
  mkdirSync(rootDir, { recursive: true });
  console.log(`>>> 创建目录：${rootDir}`);
}

// 2. 加载 schema
let schema: SchemaYaml;
if (args.mock) {
  const tmpPath = `${rootDir}/_mock.schema.yaml`;
  writeFileSync(tmpPath, mockSchemaYaml(), "utf-8");
  schema = loadSchemaYaml(tmpPath);
  console.log(`>>> mock schema 写入：${tmpPath}`);
} else {
  schema = loadSchemaYaml(args.schemaPath!);
}

// 3. 生成 .schema.sql
const schemaSql = generateSchemaSql(schema);
const schemaSqlPath = `${rootDir}/.schema.sql`;
writeFileSync(schemaSqlPath, schemaSql, "utf-8");
console.log(`>>> schema SQL 写入：${schemaSqlPath}`);

// 4. 跑 ensureSchema（幂等建表）
const result = ensureSchema(kbPath);
console.log(`>>> schema ${result.created ? "created" : "verified"}, version = v${result.version}`);

// 5. 写 slug_rule.json
const slugRulePath = `${rootDir}/.slug-rule.json`;
writeFileSync(slugRulePath, generateSlugRuleJson(schema), "utf-8");
console.log(`>>> slug rule 写入：${slugRulePath}`);

// 6. 写 README
const readmePath = `${rootDir}/README.md`;
writeFileSync(readmePath, generateReadme(schema), "utf-8");
console.log(`>>> README 写入：${readmePath}`);

// 7. 保存原始 schema.yaml（mock 也保存成 schema.yaml，保持与 ingest 期望一致）
const savedPath = `${rootDir}/schema.yaml`;
if (!existsSync(savedPath)) {
  if (args.mock) {
    writeFileSync(savedPath, mockSchemaYaml(), "utf-8");
    console.log(`>>> schema.yaml（mock）写入：${savedPath}`);
  } else if (args.schemaPath) {
    writeFileSync(savedPath, readFileSync(args.schemaPath, "utf-8"), "utf-8");
    console.log(`>>> schema.yaml 备份：${savedPath}`);
  }
}

console.log();
console.log(">>> 当前数据库状态：");
describeDb(kbPath);
console.log();
console.log(`>>> 建库完成：${kbPath}`);
console.log(`>>> 下一步：bun run scripts/ingest.ts ${kbPath} --mock`);